package com.gfashion.data.entity.homepage;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import java.util.Set;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "gf-customized-homepage")
public class GfCustomizedHomepageEntity {

    @DynamoDBHashKey(attributeName = "customerId")
    @DynamoDBAutoGeneratedKey
    private Integer customerId;

    @DynamoDBAttribute(attributeName = "recommendedProducts")
    private Set<GfHomepageProductEntity> recommendedProducts;

    @DynamoDBAttribute(attributeName = "recommendedDesigners")
    private Set<GfHomepageDesignerEntity> recommendedDesigners;

    @DynamoDBAttribute(attributeName = "recommendedBrands")
    private Set<GfHomepageBrandEntity> recommendedBrands;

    @DynamoDBAttribute(attributeName = "followingDesigners")
    private Set<GfHomepageDesignerEntity> followingDesigners;

    @DynamoDBAttribute(attributeName = "followingBrands")
    private Set<GfHomepageBrandEntity> followingBrands;

}
