package com.gfashion.data.entity.homepage;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "gf-recommendation-product")
public class GfHomepageProductEntity {

    @DynamoDBHashKey(attributeName = "productId")
    @DynamoDBAutoGeneratedKey
    private Integer productId;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "photoUrl")
    private String photoUrl;

    @DynamoDBAttribute(attributeName = "isFeatured")
    private Boolean isFeatured;
}
