stages:
  - build
  - package
  - deploy 

build:
  image: maven:ibmjava-alpine
  stage: build
  script:
  - mvn clean install
  artifacts:
    paths:
    - g-fashion-app/target
  tags: 
  - docker

.docker_build_tmpl: &docker_build_tmpl
  stage: package
  script:
  - docker build -f ${DOCKERFILE_PATH} -t 939023048332.dkr.ecr.us-east-1.amazonaws.com/${REPOSITORY}:${CI_COMMIT_SHORT_SHA} .
  - docker push 939023048332.dkr.ecr.us-east-1.amazonaws.com/${REPOSITORY}:${CI_COMMIT_SHORT_SHA}
  - docker rmi 939023048332.dkr.ecr.us-east-1.amazonaws.com/${REPOSITORY}:${CI_COMMIT_SHORT_SHA}

package:
  <<: *docker_build_tmpl
  variables:
    REPOSITORY: 'gfashion/magento-java-proxy'
    DOCKERFILE_PATH: 'docker/Dockerfile'
  tags: 
  - docker
  only:
  - master
  - develop

regversion:
  image: 939023048332.dkr.ecr.us-east-1.amazonaws.com/ops/regversion:059c89fb
  stage: deploy
  script: /regversion
  variables:
    REPO_NAME: 'gfashion-java-proxy'
    ENDPOINT: 'http://api.chatops.dev2.gfashion2020.tk/version/record/add'
    TOKEN: 'aWTUTKfApdKiU4d'
  tags:
  - docker
  only:
  - master
  - develop


deploy:
  image: curlimages/curl
  stage: deploy
  script:
  - curl remotecall.dev2.gfashion2020.tk/upgrade_java_proxy/${CI_COMMIT_SHORT_SHA} -X POST -H TOKEN:aWTUTKfApdKiU4d -v
  - curl -H TOKEN:aWTUTKfApdKiU4d http://api.chatops.dev2.gfashion2020.tk/msg/hook/707658231291576331 -d "----> New version deployed on dev2 ${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}<----" -v
  only:
  - develop
  tags: 
  - docker

