swagger: "2.0"
info:
  description: "GFashion"
  version: "1.0.0"
  title: "GFashion"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "gtv1.org"
basePath: "/v1"
tags:
  - name: "gfashion"
    description: "Everything about GFashion"
  - name: "product"
    description: "Recommended product"
  - name: "order"
    description: "Access to GFashion Store orders"
  - name: "cart"
    description: "Access to customer's cart"
  - name: "customer"
    description: "Operations about customer"
  - name: "designer"
    description: "Recommended desginer"
  - name: "category"
    description: "Access to GFashion category"
schemes:
  - "https"
  - "http"
paths:
  /products:
    post:
      tags:
        - "product"
      summary: "Add a new product to the store"
      description: ""
      operationId: "addProduct"
      security:
        - gfashionstore_auth:
            - "write:products"
            - "read:products"
    put:
      tags:
        - "product"
      summary: "Update an existing product"
      description: ""
      operationId: "updateProduct"
      security:
        - gfashionstore_auth:
            - "write:products"
            - "read:products"
  /channelProducts/:
    get:
      tags:
        - "product"
      summary: "Searches Products by given query string"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "searchProducts"
      security:
        - gfashionstore_auth:
            - "write:products"
            - "read:products"
  /products/searchByDesigner/{designerId}:
    get:
      tags:
        - "product"
      summary: "Searches Products by Designer Id"
      operationId: "searchProductsByDesigner"
      security:
        - gfashionstore_auth:
            - "write:products"
            - "read:products"
  /products/{productId}:
    get:
      tags:
        - "product"
      summary: "Find product by ID"
      description: "Returns a single product"
      operationId: "getProdutById"
      security:
        - api_key: []
    post:
      tags:
        - "product"
      summary: "Updates a product in the store with form data"
      description: ""
      operationId: "updateProductWithForm"
      security:
        - gfashionstore_auth:
            - "write:products"
            - "read:products"
    delete:
      tags:
        - "product"
      summary: "Deletes a product"
      description: ""
      operationId: "deleteProduct"
      security:
        - gfashionstore_auth:
            - "write:products"
            - "read:products"
  /products/{productId}/uploadImage:
    post:
      tags:
        - "product"
      summary: "uploads an image"
      description: ""
      operationId: "uploadProductFile"
      security:
        - gfashionstore_auth:
            - "write:products"
            - "read:products"

  /orders:
    post:
      tags:
        - "order"
      summary: "Place an order for a product"
      description: ""
      operationId: "placeOrder"
  /orders/{orderId}:
    get:
      tags:
        - "order"
      summary: "Find purchase order by orderID"
      description: "For valid response try integer IDs with value >= 1 and <= 10. Other values will generate exceptions"
      operationId: "getOrderById"
    delete:
      tags:
        - "order"
      summary: "Delete purchase order by orderID"
      description: "For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors"
      operationId: "deleteOrder"
  /orders/ordersOfCustomer/{customerId}:
    get:
      tags:
        - "order"
      summary: "Find purchase orders by customerId"
      description: "For valid response try integer IDs with value >= 1 and <= 10. Other values will generate exceptions"
      operationId: "getOrdersByCustomerId"
  /store/storeViews:
    get:
      tags:
        - "store"
      summary: "Retrieve list of all stores"
      description: ""
      operationId: "getStoreViews"
      # No parameters:
  /store/websites:
    get:
      tags:
        - "store"
      summary: "Retrieve list of all websites"
      description: ""
      operationId: "getWebsites"
      # No parameters:
  /store/storeGroups:
    get:
      tags:
        - "store"
      summary: "Retrieve list of all groups"
      description: ""
      operationId: "getStoreGroups"
      # No parameters:
  /store/StoreConfigs:
    get:
      tags:
        - "store"
      summary: "Retrieve list of all store configurations"
      description: ""
      operationId: "getStoreConfigs"
      # No parameters:
  /carts/productsOf/{customerId}:
    get:
      tags:
        - "cart"
      summary: "Find all products in the shopping cart by customerId"
      description: "For valid response try integer IDs with value >= 1 and <= 10. Other values will generate exceptions"
      operationId: "getProductsinCartByCustomerId"
  /carts/{customerId}/{productId}:
    post:
      tags:
        - "cart"
      summary: "Add an product to the shopping cart of a customer with customerId"
      description: "For valid response try integer IDs with value >= 1 and <= 10. Other values will generate exceptions"
      operationId: "addProducttoCartByCustomerId"
    delete:
      tags:
        - "cart"
      summary: "Delete an product From the shopping cart of a customer with customerId"
      description: "For valid response try integer IDs with value >= 1 and <= 10. Other values will generate exceptions"
      operationId: "deleteProducttoCartByCustomerId"
  /customers:
    post:
      tags:
        - "customer"
      summary: "Create customer"
      description: "This can only be done by the logged in customer."
      operationId: "createCustomer"
  /customers/createWithArray:
    post:
      tags:
        - "customer"
      summary: "Creates list of customers with given input array"
      description: "not sure when this api is needed"
      operationId: "createCustomersWithArrayInput"
  /customers/createWithList:
    post:
      tags:
        - "customer"
      summary: "Creates list of customers with given input array"
      description: "not sure when this api is needed"
      operationId: "createCustomersWithListInput"
  /customers/login:
    get:
      tags:
        - "customer"
      summary: "Logs customer into the system"
      description: ""
      operationId: "loginCustomer"
  /customers/logout:
    get:
      tags:
        - "customer"
      summary: "Logs out current logged in customer session"
      description: ""
      operationId: "logoutCustomer"
  /customers/{customerid}:
    get:
      tags:
        - "customer"
      summary: "Get customer by customer name"
      description: ""
      operationId: "getCustomerByName"
    put:
      tags:
        - "customer"
      summary: "Update customer"
      description: "This can only be done by the logged in customer."
      operationId: "updateCustomer"
    delete:
      tags:
        - "customer"
      summary: "Delete customer"
      description: "This can only be done by the logged in customer."
      operationId: "deleteCustomer"
  /designers:
    post:
      tags:
        - "designer"
      summary: "Add a new designer to the store"
      description: ""
      operationId: "adddesigner"
      security:
        - gfashionstore_auth:
            - "write:designers"
            - "read:designers"
    put:
      tags:
        - "designer"
      summary: "Update an existing designer"
      description: ""
      operationId: "updatedesigner"
      security:
        - gfashionstore_auth:
            - "write:designers"
            - "read:designers"
  /designers/search:
    get:
      tags:
        - "designer"
      summary: "Searches designers by given query string"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "searchdesigners"
      security:
        - gfashionstore_auth:
            - "write:designers"
            - "read:designers"
  /designers/{designerId}:
    get:
      tags:
        - "designer"
      summary: "Find designer by ID"
      description: "Returns a single designer"
      operationId: "getDesignerById"
      security:
        - api_key: []
    post:
      tags:
        - "designer"
      summary: "Updates a designer in the store with form data"
      description: ""
      operationId: "updatedesignerWithForm"
      security:
        - gfashionstore_auth:
            - "write:designers"
            - "read:designers"
    delete:
      tags:
        - "designer"
      summary: "Deletes a designer"
      description: ""
      operationId: "deletedesigner"
      security:
        - gfashionstore_auth:
            - "write:designers"
            - "read:designers"
  /designers/{designerId}/uploadImage:
    post:
      tags:
        - "designer"
      summary: "uploads an image"
      description: ""
      operationId: "uploadDesignerFile"
      security:
        - gfashionstore_auth:
            - "write:designers"
            - "read:designers"

  /category/list:
    get:
      tags:
        - "category"
      summary: "List category "
      description: "Get category list"
      operationId: "getAllCategory"
      security:
        - api_key: []
  /category/{categoryId}:
    get:
      tags:
        - "category"
      summary: "Find category by categoryId"
      description: "Get info about category by category id"
      operationId: "getCategoryInfoById"
      security:
        - api_key: []

  /category/{categoryId}/products:
    get:
      tags:
        - "category"
      summary: "Find Products by categoryId"
      description: "Get products assigned to category"
      operationId: "getProductsByCategoryId"
      security:
        - api_key: []
    post:
      tags:
        - "category"
      summary: "Assign a product to the required category"
      description: "Assign a product to the required category"
      operationId: "updagteProductsByCategoryId"
      security:
        - gfashionstore_auth:
            - "write:categories"
            - "read:categories"
    delete:
      tags:
        - "category"
      summary: "Assign a product to the required category"
      description: "Assign a product to the required category"
      operationId: "updagteProductsByCategoryId1"
      security:
        - gfashionstore_auth:
            - "write:categories"
            - "read:categories"

securityDefinitions:
  gfashionstore_auth:
    type: "oauth2"
    authorizationUrl: "http://gfashionstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:products: "modify products in your account"
      read:products: "read your products"
      write:designers: "modify designers in your account"
      read:designers: "read your designers"
      write:categories: "modify categories in your account"
      read:categories: "read your categories"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"