swagger: "2.0"
info:
  description: "GFashion"
  version: "1.0.0"
  title: "GFashion"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "gtv1.org"
basePath: "/v1"
tags:
  - name: "gfashion"
    description: "Everything about GFashion"
  - name: "product"
    description: "Recommended product"
  - name: "order"
    description: "Access to GFashion Store orders"
  - name: "cart"
    description: "Access to customer's cart"
  - name: "customer"
    description: "Operations about customer"
  - name: "designer"
    description: "Recommended desginer"
schemes:
  - "https"
  - "http"
paths:
  /product:
    post:
      tags:
        - "product"
      summary: "Add a new product to the store"
      description: ""
      operationId: "addProduct"
      security:
        - gfashionstore_auth:
            - "write:products"
            - "read:products"
    put:
      tags:
        - "product"
      summary: "Update an existing product"
      description: ""
      operationId: "updateProduct"
      security:
        - gfashionstore_auth:
            - "write:products"
            - "read:products"
  /product/search:
    get:
      tags:
        - "product"
      summary: "Searches Products by given query string"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "searchProducts"
      security:
        - gfashionstore_auth:
            - "write:products"
            - "read:products"
  /product/searchByDesigner/{designerId}:
    get:
      tags:
        - "product"
      summary: "Searches Products by Designer Id"
      operationId: "searchProductsByDesigner"
      security:
        - gfashionstore_auth:
            - "write:products"
            - "read:products"
  /product/{productId}:
    get:
      tags:
        - "product"
      summary: "Find product by ID"
      description: "Returns a single product"
      operationId: "getProdutById"
      security:
        - api_key: []
    post:
      tags:
        - "product"
      summary: "Updates a product in the store with form data"
      description: ""
      operationId: "updateProductWithForm"
      security:
        - gfashionstore_auth:
            - "write:products"
            - "read:products"
    delete:
      tags:
        - "product"
      summary: "Deletes a product"
      description: ""
      operationId: "deleteProduct"
      security:
        - gfashionstore_auth:
            - "write:products"
            - "read:products"
  /product/{productId}/uploadImage:
    post:
      tags:
        - "product"
      summary: "uploads an image"
      description: ""
      operationId: "uploadProductFile"
      security:
        - gfashionstore_auth:
            - "write:products"
            - "read:products"

  /order:
    post:
      tags:
        - "order"
      summary: "Place an order for a product"
      description: ""
      operationId: "placeOrder"
  /order/{orderId}:
    get:
      tags:
        - "order"
      summary: "Find purchase order by orderID"
      description: "For valid response try integer IDs with value >= 1 and <= 10. Other values will generate exceptions"
      operationId: "getOrderById"
    delete:
      tags:
        - "order"
      summary: "Delete purchase order by orderID"
      description: "For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors"
      operationId: "deleteOrder"
  /order/ordersOfCustomer/{customerId}:
    get:
      tags:
        - "order"
      summary: "Find purchase orders by customerId"
      description: "For valid response try integer IDs with value >= 1 and <= 10. Other values will generate exceptions"
      operationId: "getOrdersByCustomerId"
  /cart/productsOf/{customerId}:
    get:
      tags:
        - "cart"
      summary: "Find all products in the shopping cart by customerId"
      description: "For valid response try integer IDs with value >= 1 and <= 10. Other values will generate exceptions"
      operationId: "getProductsinCartByCustomerId"
  /cart/{customerId}/{productId}:
    post:
      tags:
        - "cart"
      summary: "Add an product to the shopping cart of a customer with customerId"
      description: "For valid response try integer IDs with value >= 1 and <= 10. Other values will generate exceptions"
      operationId: "addProducttoCartByCustomerId"
    delete:
      tags:
        - "cart"
      summary: "Delete an product From the shopping cart of a customer with customerId"
      description: "For valid response try integer IDs with value >= 1 and <= 10. Other values will generate exceptions"
      operationId: "deleteProducttoCartByCustomerId"
  /customer:
    post:
      tags:
        - "customer"
      summary: "Create customer"
      description: "This can only be done by the logged in customer."
      operationId: "createCustomer"
  /customer/createWithArray:
    post:
      tags:
        - "customer"
      summary: "Creates list of customers with given input array"
      description: "not sure when this api is needed"
      operationId: "createCustomersWithArrayInput"
  /customer/createWithList:
    post:
      tags:
        - "customer"
      summary: "Creates list of customers with given input array"
      description: "not sure when this api is needed"
      operationId: "createCustomersWithListInput"
  /customer/login:
    get:
      tags:
        - "customer"
      summary: "Logs customer into the system"
      description: ""
      operationId: "loginCustomer"
  /customer/logout:
    get:
      tags:
        - "customer"
      summary: "Logs out current logged in customer session"
      description: ""
      operationId: "logoutCustomer"
  /customer/{customerid}:
    get:
      tags:
        - "customer"
      summary: "Get customer by customer name"
      description: ""
      operationId: "getCustomerByName"
    put:
      tags:
        - "customer"
      summary: "Update customer"
      description: "This can only be done by the logged in customer."
      operationId: "updateCustomer"
    delete:
      tags:
        - "customer"
      summary: "Delete customer"
      description: "This can only be done by the logged in customer."
      operationId: "deleteCustomer"
  /designer:
    post:
      tags:
        - "designer"
      summary: "Add a new designer to the store"
      description: ""
      operationId: "adddesigner"
      security:
        - gfashionstore_auth:
            - "write:designers"
            - "read:designers"
    put:
      tags:
        - "designer"
      summary: "Update an existing designer"
      description: ""
      operationId: "updatedesigner"
      security:
        - gfashionstore_auth:
            - "write:designers"
            - "read:designers"
  /designer/search:
    get:
      tags:
        - "designer"
      summary: "Searches designers by given query string"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "searchdesigners"
      security:
        - gfashionstore_auth:
            - "write:designers"
            - "read:designers"
  /designer/{designerId}:
    get:
      tags:
        - "designer"
      summary: "Find designer by ID"
      description: "Returns a single designer"
      operationId: "getDesignerById"
      security:
        - api_key: []
    post:
      tags:
        - "designer"
      summary: "Updates a designer in the store with form data"
      description: ""
      operationId: "updatedesignerWithForm"
      security:
        - gfashionstore_auth:
            - "write:designers"
            - "read:designers"
    delete:
      tags:
        - "designer"
      summary: "Deletes a designer"
      description: ""
      operationId: "deletedesigner"
      security:
        - gfashionstore_auth:
            - "write:designers"
            - "read:designers"
  /designer/{designerId}/uploadImage:
    post:
      tags:
        - "designer"
      summary: "uploads an image"
      description: ""
      operationId: "uploadDesignerFile"
      security:
        - gfashionstore_auth:
            - "write:designers"
            - "read:designers"

securityDefinitions:
  gfashionstore_auth:
    type: "oauth2"
    authorizationUrl: "http://gfashionstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:products: "modify products in your account"
      read:products: "read your products"
      write:designers: "modify designers in your account"
      read:designers: "read your designers"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"