swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "GFashion product detail swagger API "
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/"
tags:
  - name: "gfashion"
    description: "Everything about your productdetail"
    externalDocs:
      description: "Find out more"
      url: "http://swagger.io"
schemes:
  - "https"
  - "http"
paths:
  /gfashion/product/{sku}:
    get:
      tags:
        - "gfashion"
      summary: "Find pet by sku"
      description: "Returns a single productdetail"
      operationId: "getPetById"
      produces:
        - "application/json"
      parameters:
        - name: "sku"
          in: "path"
          description: "sku of productdetail to return"
          required: true
          type: "string"
          format: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/productdetail"
        "400":
          description: "Invalid sku supplied"
        "404":
          description: "productdetail not found"
      security:
        - api_key: []
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  productdetail:
    type: "object"
    required:
      - "name"
      - "photoUrls"
    properties:
      purchase_number_limit:
        type: "string"
        format: "int64"
      images:
        $ref: "#/definitions/images"
      price:
        type: "string"
        example: "32"
      name:
        type: "string"
        example: "Strive Shoulder"
      description:
        type: "string"
        example: "<p>Convenience is next to nothing when your day is crammed with action. So whether you're heading to class, gym, or the unbeaten path, make sure you've got your Strive Shoulder Pack stuffed with all your essentials, and extras as well.</p>\r\n<ul>\r\n<li>Zippered main compartment.</li>\r\n<li>Front zippered pocket.</li>\r\n<li>Side mesh pocket.</li>\r\n<li>Cell phone pocket on strap.</li>\r\n<li>Adjustable shoulder strap and top carry handle.</li>\r\n</ul>"
      designer_name:
        type: "string"
        example: ""
      brand_name:
        type: "string"
        example: ""
      brand_link:
        type: "string"
        example: ""
      attribute:
        type: "array"
        xml:
          name: "tag"
          wrapped: true
        items:
          $ref: "#/definitions/attribute"
      designer_link:
        type: "string"
        example: ""
      product_links:
        type: "array"
        xml:
          name: "tag"
          wrapped: true
        items:
          $ref: "#/definitions/product_links"
  product_links:
    type: "object"
    properties:
      link_type:
        type: "string"
        example: "crosssell"
      image:
        type: "string"
        example: "/u/g/ug04-bk-0.jpg"
      linked_product_sku:
        type: "string"
        example: "24-UG04"
      linked_product_type:
        type: "string"
        example: "simple"
      name:
        type: "string"
        example: "Pushup Grips"
      position:
        type: "integer"
        example: 2
      sku:
        type: "string"
        example: "24-MB04"
    xml:
      name: "product_links"
  images:
    type: "object"
    properties:
      types:
        type: "array"
        format: "string"
        items:
          $ref: "#/definitions/types"
      file:
        type: "string"
        example: "/u/g/ug04-bk-0.jpg"
      media_type:
        type: "string"
        example: "image"
      disabled:
        type: "boolean"
        example: false
      id:
        type: "integer"
        format: "int64"
      label:
        type: "string"
      position:
        type: "integer"
        format: "int64"
    xml:
      name: "images"
  types:
    type: "object"
    properties:
      image:
        type: "string"
      small_image:
        type: "string"
      thumbnail:
        type: "string"
  attribute:
    type: "object"
    properties:
      value:
        type: "string"
        format: "int64"
      attribute_code:
        type: "string"
        example: "color"
    xml:
      name: "attribute"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
