package com.gfashion.data;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

/**
 * 客服表
 *
 * @author ：勉强生
 * @description：TODO
 * @date ：2020/6/7 15:43
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "gfContactUs")
//@Document(indexName="gfContactUs")
public class GfContactUsEntity {

//    @Id
    @DynamoDBHashKey(attributeName = "gfContactUsId")
    @DynamoDBAutoGeneratedKey
    private String gfContactUsId; //ID

    @DynamoDBAttribute(attributeName = "gfCustomerId")
    private String gfCustomerId; //用户ID

    @DynamoDBAttribute(attributeName = "gfOrderId")
    private String gfOrderId; //订单ID

    @DynamoDBAttribute(attributeName = "type")
    private Integer type; //咨询种类

    @DynamoDBAttribute(attributeName = "title")
    private String title; //标题

    @DynamoDBAttribute(attributeName = "contentOfInquiry")
    private String contentOfInquiry; //咨询内容

    @DynamoDBAttribute(attributeName = "status")
    private Integer status; //状态 1新增数据/ 2客服处理中 /3 已解决（答复客户）/ 4客户处理中

    @DynamoDBAttribute(attributeName = "createTime")
//    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
//    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private String createTime; //生成时间

    @DynamoDBAttribute(attributeName = "updateTime")
//    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
//    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private String updateTime; //更新时间

}