package com.gfashion.data;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

@Setter
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "gfDesigner")
public class GfDesignerEntity {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "bigCategory")
    private String bigCategory;

    @DynamoDBAttribute(attributeName = "brief")
    private String brief;

    @DynamoDBAttribute(attributeName = "photoUrl")
    private String photoUrl;

    @DynamoDBAttribute(attributeName = "language")
    private String language;

    @DynamoDBAttribute(attributeName = "onSale")
    private String onSale;

    @DynamoDBAttribute(attributeName = "country")
    private String country;

    @DynamoDBAttribute(attributeName = "recommends")
    private String recommends;

    @DynamoDBAttribute(attributeName = "cooperatingBrands")
    private String cooperatingBrands;

    @DynamoDBAttribute(attributeName = "link")
    private String link;

    @DynamoDBAttribute(attributeName = "forMan")
    private Boolean forMan;

    @DynamoDBAttribute(attributeName = "forWoman")
    private Boolean forWoman;

}
