package com.gfashion.data;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "gf-products")
public class GfProductEntity {

    @DynamoDBHashKey(attributeName = "productId")
    @DynamoDBAutoGeneratedKey
    private String productId;

    @DynamoDBAttribute(attributeName = "productName")
    private String productName;

    @DynamoDBAttribute(attributeName = "productBrand")
    private String productBrand;

    @DynamoDBAttribute(attributeName = "productDelete")
    private String productDelete;

    @DynamoDBAttribute(attributeName = "productPrice")
    private String productPrice;

    @DynamoDBAttribute(attributeName = "productBrief")
    private String productBrief;

    @DynamoDBAttribute(attributeName = "productCategory")
    private String productCategory;

    @DynamoDBAttribute(attributeName = "productCreatedat")
    private String productCreatedat;

    @DynamoDBAttribute(attributeName = "productUpdatedat")
    private String productUpdatedat;
}
