package com.gfashion.data;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import java.math.BigDecimal;
import java.util.List;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "gfProduct")
public class GfProductEntity {
    //主键
    @DynamoDBHashKey(attributeName = "id")
    private String id;

    //产品id,也可叫做spuID,或者父SkuId，这里1个productId对应多个skuID
    @DynamoDBAttribute(attributeName = "productId")
    private String productId;

    //产品条码
    @DynamoDBAttribute(attributeName = "productCode")
    private String productCode;

    //产品名称
    @DynamoDBAttribute(attributeName = "productName")
    private String productName;

    //语言
    @DynamoDBAttribute(attributeName = "language")
    private String language;

    //三级分类id 此处考虑是否拆分成3个字段，third second first，或者添加一张category表。
    @DynamoDBAttribute(attributeName = "categoryId")
    private Integer categoryId;

    //设计师id
    @DynamoDBAttribute(attributeName = "designerId")
    private String designerId;

    //设计师名称
    @DynamoDBAttribute(attributeName = "designerName")
    private String designerName;

    //设计师链接
    @DynamoDBAttribute(attributeName = "designerLink")
    private String designerLink;

    //大类
    @DynamoDBAttribute(attributeName = "mainCategory")
    private String mainCategory;

    //币种
    @DynamoDBAttribute(attributeName = "currency")
    private String currency;

    //是否第三方发货
    @DynamoDBAttribute(attributeName = "isDeliveryByThirdParty")
    private boolean isDeliveryByThirdParty;

    //原价
    @DynamoDBAttribute(attributeName = "price")
    private BigDecimal price;

    //gClub会员价
    @DynamoDBAttribute(attributeName = "gclubMemberPrice")
    private BigDecimal gclubMemberPrice;

    //二次折扣价
    @DynamoDBAttribute(attributeName = "discountPrice")
    private BigDecimal discountPrice;

    //图片地址
    @DynamoDBAttribute(attributeName = "images")
    private List<String> images;

    //限购数量
    @DynamoDBAttribute(attributeName = "purchaseNumber")
    private Integer purchaseNumber;

    //限购数量 是否可见
    @DynamoDBAttribute(attributeName = "isPurchaseNumberVisible")
    private boolean isPurchaseNumberVisible;

    //编辑笔记
    @DynamoDBAttribute(attributeName = "editNotes")
    private String editNotes;

    //细节与养护
    @DynamoDBAttribute(attributeName = "conservation")
    private String conservation;

    //尺码信息
    @DynamoDBAttribute(attributeName = "specification")
    private String specification;

    //购买须知
    @DynamoDBAttribute(attributeName = "postSale")
    private String postSale;

    //是否可以二次打折
    @DynamoDBAttribute(attributeName = "isDiscount")
    private boolean isDiscount;
}
