package com.gfashion.data;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.gfashion.domain.product.GfMediaGalleryEntry;
import lombok.*;

import java.math.BigDecimal;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "gfvendor")
public class GfVendorEntity {

    @DynamoDBHashKey(attributeName = "vendorId")
    @DynamoDBAutoGeneratedKey
    private String vendorId;

    @DynamoDBAttribute(attributeName = "vendorName")
    private String vendorName;

    @DynamoDBAttribute(attributeName = "brief")
    private String brief;

    @DynamoDBAttribute(attributeName = "photoUrl")
    private String photoUrl;

    @DynamoDBAttribute(attributeName = "recommends")
    private String recommends;

    @DynamoDBAttribute(attributeName = "vendor_login_id")
    private String vendor_login_id;
//    private JSONObject extension_attributes;

    /**
     *  todo eric, dynamodb support using complex object to store, need check ES support complex object.
     */
}
