package com.gfashion.data;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

@Getter
@Setter
@ToString
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "DDBOperationLog")
public class LogEntity {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private String id;

    @DynamoDBAttribute(attributeName = "operationDate")
    private String operationDate;

    @DynamoDBAttribute(attributeName = "requestType")
    private String requestType; //HTTP_METHOD

    @DynamoDBAttribute(attributeName = "operationUrl")
    private String operationUrl;

    @DynamoDBAttribute(attributeName = "operationClass")
    private String operationClass;

    @DynamoDBAttribute(attributeName = "magentoProductId")
    private String magentoProductId;

    @DynamoDBAttribute(attributeName = "requestRawInfo")
    private String requestRawInfo; //request.getinputStream

    @DynamoDBAttribute(attributeName = "requestObjectInfo")
    private String requestObjectInfo; //joinPoint.getArgs

    @DynamoDBAttribute(attributeName = "responseInfo")
    private String responseInfo;

    @DynamoDBAttribute(attributeName = "exceptionInfo")
    private String exceptionInfo;

    //for custom tag.
    @DynamoDBAttribute(attributeName = "operationType")
    private String operationType;

    @DynamoDBAttribute(attributeName = "operationEvent")
    private String operationEvent;
}
