# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  profiles:
    active: dev
#  redis:
#    database: 1
#    host: 192.168.71.71
#    port: 6379
#    password:
#    timeout: 5000
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0
#    session:
#      store-type: none
  # 使用redis集群
  #  redis:
  #    database: 0
  #    cluster:
  #      nodes: 192.168.71.71:7001,192.168.71.71:7002,192.168.71.71:7003,192.168.71.71:7004,192.168.71.71:7005,192.168.71.71:7006
  #    jedis:
  #      pool:
  #        max-idle: 8
  #        max-wait: -1
  #        min-idle: 0
  #    timeout: 5000
  #    session:
  #      store-type: redis
---
spring:
  profiles: dev
server:
  port: 8080

magento:
  url:
    base: http://magento2.dev3.gfashion2020.tk/index.php/rest/V1/
    adminToken: integration/admin/token
    customerToken: integration/customer/token
    customers: customers/
    customerMe: customers/me
    customerChangePassword: me/password
    carts: carts/mine/
    storeViews: store/storeViews/
    websites: store/websites/
    storeGroups: store/storeGroups/
    storeConfigs: store/storeConfigs/
    products: products/
    shipment: shipment/
    order: order/
    stockItems: stockItems/
    categories: categories/
    attributes: attributes/
    locale:
      en: 1
      zh: 6
    listCategories: categories/list
    parameters:
      parentIdField: parent_id
      field: searchCriteria[filterGroups][%d][filters][%d][field]=
      value: searchCriteria[filterGroups][%d][filters][%d][value]=
      conditionType: searchCriteria[filterGroups][%d][filters][%d][condition_type]=
      englishRootCategory: 65
      chineseRootCategory: 65
      rootCategoryLevel: 1
      supportLanguages: en,cn
      recommendedDesignersParentId: 62 # the category id for designers
      recommendedBrandsParentId: 59 # the category id for brands
    designersParentId: 46
    brandsParentId: 50
  username: admin
  password: magentorocks1

test:
  email: customer@test.com
  password: P@ssw0rd

logging:
  level:
    ROOT: DEBUG
    com.gfashion: DEBUG

aws:
  dynamodb:
    accesskey: AKIA5VIRCT2GP56W4WU6
    secretkey: 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
    session_token:
    endpoint: https://dynamodb.us-east-1.amazonaws.com
    region: us-east-1
  es:
    endpoint: https://search-gfproductdomain-bd4u3hhprgsfnhwek2wihxfvxq.us-east-1.es.amazonaws.com
    accessKey: AKIA5VIRCT2GP56W4WU6
    secretKey: ozKKR7m0/We/zpQ0Qne3ERYXpXYVs4AWE8rDD3vu
    region: us-east-1
    serviceName: es
  samples:
    #brands: 4d8b996e-7d31-4463-ac32-03e48af71eb9,22141eab-f9f8-43bb-bc80-3867b4fc8350,cefa93e2-05d9-4f13-8824-7532cf91a544,0b6bd4e4-d3c1-45ed-80a6-981f4b63e0e2,53c27c88-f394-4297-8244-c37766905ab1
    designers: 9c72345e-d67b-4210-ba83-77666bcaf8a9,e964bae3-98a1-47d0-958f-fb06a84ad1c7,3169cbba-15e6-4c1c-a04b-bee552784efa,f6d09284-1eef-458c-9022-5fe1b680dd3d,94bbb5e3-39c5-4cd2-a8bb-508a1010af98,09c2da08-bed7-4bd2-bae3-80c61ae2cfe9,a3ee43dc-3283-4258-9cc5-c503f906b8d0,2f159f5c-8181-4ade-b7fd-28dcedd935bb
    products: 813354b7-5dc0-4874-8231-6c4d00433709,61af3f6d-c3ad-4a44-af37-21a4e3dc3da2,cc34ed34-51de-4979-9a4d-8a79e51e8d87,60a08abf-0964-4324-a175-89baf7213145,03255fe2-ae54-48ba-b20c-a4e4f05a2004,0b41c0d7-8bca-483f-8e15-5885dce3aa65
    #brandsCn: 17745895-1149-4b09-b85f-59033e0a67a0,2ef28ac3-9513-44f5-88c0-4053d4156f34,6493453d-fc78-4ef6-bb3f-69628f9ca279,a2382cc0-464f-4bcc-8251-8d7bcf9467e0,dd2e8567-d822-488b-bfd0-3a4b0ed80d4e
    designersCn: fd51b2f6-9db4-4e4a-9c34-13b682679d5e,122b9de6-30d0-4091-a2a4-459c992204f8,77ee191a-6e34-45c2-83e1-bbcd8902b898,2269ae53-e187-42fa-bf03-14bff6295636,54dd0b9f-463e-4486-98cf-afd087bd299a,cf9529a4-9ea3-429c-8b11-f2051fda9c81,23e2b020-f38a-4572-87f4-057a69361c19,28c2f2d3-2df6-43fa-b816-de44edef6c53
    productsCn: 5b41cc15-9556-4bac-b67a-afb5ff9a4092,df07c02a-774c-4f28-9d30-733fbd4eb84a,3653d7fa-f572-4a48-a9d2-1b2347c90a01,89cdefa1-3548-414e-95d3-dec3a662bd93,2ffdb02c-17e5-4a70-9a7b-1070e59e0929,6b864bcc-ab65-4ec0-a741-6468cb3fd628

sendgrid:
  api:
    key: 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
    length: 6
    project: GFashion
    type: Change Email Address
    senderEmail: support@gfashion2020.tk

---
spring:
  profiles: qa
server:
  port: 8080

magento:
  url:
    base: http://magento2.dev3.gfashion2020.tk/index.php/rest/V1/
    adminToken: integration/admin/token
    customerToken: integration/customer/token
    customers: customers/
    customerMe: customers/me
    changePassword: customers/me/password
    carts: carts/mine/
    storeViews: store/storeViews/
    websites: store/websites/
    storeGroups: store/storeGroups/
    storeConfigs: store/storeConfigs/
    products: products/
    shipment: shipment/
    order: order/
    stockItems: stockItems/
    categories: categories/
    attributes: products/attributes?searchCriteria[filterGroups][0][filters][0][field]=is_filterable&searchCriteria[filterGroups][0][filters][0][value]=false&searchCriteria[filterGroups][0][filters][0][conditionType]=neq
    locale:
      us: 1
      cn: 6
    listCategories: categories/list
    parameters:
      parentIdField: parent_id
      field: searchCriteria[filterGroups][%d][filters][%d][field]=
      value: searchCriteria[filterGroups][%d][filters][%d][value]=
      conditionType: searchCriteria[filterGroups][%d][filters][%d][condition_type]=
      englishRootCategory: 65
      chineseRootCategory: 65
      rootCategoryLevel: 1
      supportLanguages: en,cn
      recommendedDesignersParentId: 62 # the category id for designers
      recommendedBrandsParentId: 59 # the category id for brands
    designersParentId: 46
    brandsParentId: 50

logging:
  level:
    ROOT: DEBUG
    com.gfashion: DEBUG

aws:
  dynamodb:
    accesskey: AKIA5VIRCT2GP56W4WU6
    secretkey: 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
    session_token:
    endpoint: https://dynamodb.us-east-1.amazonaws.com
    region: us-east-1
  es:
    endpoint: https://search-gfproductdomain-bd4u3hhprgsfnhwek2wihxfvxq.us-east-1.es.amazonaws.com
    accessKey: AKIA5VIRCT2GP56W4WU6
    secretKey: ozKKR7m0/We/zpQ0Qne3ERYXpXYVs4AWE8rDD3vu
    region: us-east-1
    serviceName: es
  samples:
    brands: 4d8b996e-7d31-4463-ac32-03e48af71eb9,22141eab-f9f8-43bb-bc80-3867b4fc8350,cefa93e2-05d9-4f13-8824-7532cf91a544,0b6bd4e4-d3c1-45ed-80a6-981f4b63e0e2,53c27c88-f394-4297-8244-c37766905ab1
    designers: 22f6a794-9a6f-4b1b-b5ff-78c7766f5d0e,a20fd425-aa13-4f18-834a-38bafce4031b,23fa1c1e-fbcf-466f-adf1-4fc824255954,a49ba01e-2c6f-49c4-a823-e9dcbbbeee34,629524b1-d299-4e83-b216-e99afc083764,2826d6c4-6700-41d8-8932-8d8f5d4fe261,c9d7b743-50c5-4266-9bdf-228924e311ec,20891b85-a4dd-4ece-990e-bb227e2a316c
    products: 813354b7-5dc0-4874-8231-6c4d00433709,61af3f6d-c3ad-4a44-af37-21a4e3dc3da2,cc34ed34-51de-4979-9a4d-8a79e51e8d87,60a08abf-0964-4324-a175-89baf7213145,03255fe2-ae54-48ba-b20c-a4e4f05a2004,0b41c0d7-8bca-483f-8e15-5885dce3aa65
    brandsCn: 17745895-1149-4b09-b85f-59033e0a67a0,2ef28ac3-9513-44f5-88c0-4053d4156f34,6493453d-fc78-4ef6-bb3f-69628f9ca279,a2382cc0-464f-4bcc-8251-8d7bcf9467e0,dd2e8567-d822-488b-bfd0-3a4b0ed80d4e
    designersCn: 3abe5b1b-a546-4fc2-9944-892dd6dd8701,e9fc8d44-b357-40e0-9205-444ad407923a,c07610ae-80a1-492a-bd6a-e9ac9eda19ce,284f5726-a400-4792-b97c-e5a78f7651c6,02fd1437-db98-48bb-a998-926049da7841,8a7e61d6-adb2-42e7-8fe0-d4f2c4b28088,e85ee700-8c47-4f13-85e3-243df5d716f8,5c39ce6d-3a92-4dd5-b08b-844da9079eab
    productsCn: 5b41cc15-9556-4bac-b67a-afb5ff9a4092,df07c02a-774c-4f28-9d30-733fbd4eb84a,3653d7fa-f572-4a48-a9d2-1b2347c90a01,89cdefa1-3548-414e-95d3-dec3a662bd93,2ffdb02c-17e5-4a70-9a7b-1070e59e0929,6b864bcc-ab65-4ec0-a741-6468cb3fd628

sendgrid:
  api:
    key: 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
    length: 6
    project: GFashion
    type: Change Email Address
    senderEmail: support@gfashion2020.tk
