# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 8080

magento:
  url:
    base: https://www.gfashion2020.tk/index.php/rest/V1/
    token: integration/admin/token
    customers: customers/
    storeViews: store/storeViews/
    websites: store/websites/
    storeGroups: store/storeGroups/
    storeConfigs: store/storeConfigs/
    products: products/
    stockItems: stockItems/
    categories: categories/
    attributes: attributes/
    locale:
      en: 1
      zh: 6
    listCategories: categories/list
    parameters:
      parentIdField: parent_id
      field: searchCriteria[filterGroups][0][filters][0][field]=
      value: searchCriteria[filterGroups][0][filters][0][value]=
      recommendedDesignersParentId: 62 # the category id for designers
      recommendedBrandsParentId: 59 # the category id for brands
    designersParentId: 46
    brandsParentId: 50
  username: admin
  password: 202064_Hh

logging:
  level:
    ROOT: DEBUG
    com.gfashion: DEBUG

aws:
  dynamodb:
    accesskey: AKIA5VIRCT2GP56W4WU6
    secretkey: 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
    session_token:
    endpoint: https://dynamodb.us-east-1.amazonaws.com
    region: us-east-1
  es:
    endpoint: https://search-gfproductdomain-bd4u3hhprgsfnhwek2wihxfvxq.us-east-1.es.amazonaws.com
    accessKey: AKIA5VIRCT2GP56W4WU6
    secretKey: ozKKR7m0/We/zpQ0Qne3ERYXpXYVs4AWE8rDD3vu
    region: us-east-1
    serviceName: es
  samples:
    brands: 4d8b996e-7d31-4463-ac32-03e48af71eb9,22141eab-f9f8-43bb-bc80-3867b4fc8350,cefa93e2-05d9-4f13-8824-7532cf91a544,0b6bd4e4-d3c1-45ed-80a6-981f4b63e0e2,53c27c88-f394-4297-8244-c37766905ab1
    designers: 22f6a794-9a6f-4b1b-b5ff-78c7766f5d0e,a20fd425-aa13-4f18-834a-38bafce4031b,23fa1c1e-fbcf-466f-adf1-4fc824255954,a49ba01e-2c6f-49c4-a823-e9dcbbbeee34,629524b1-d299-4e83-b216-e99afc083764,2826d6c4-6700-41d8-8932-8d8f5d4fe261,c9d7b743-50c5-4266-9bdf-228924e311ec,20891b85-a4dd-4ece-990e-bb227e2a316c
    products: 813354b7-5dc0-4874-8231-6c4d00433709,61af3f6d-c3ad-4a44-af37-21a4e3dc3da2,cc34ed34-51de-4979-9a4d-8a79e51e8d87,60a08abf-0964-4324-a175-89baf7213145,03255fe2-ae54-48ba-b20c-a4e4f05a2004,0b41c0d7-8bca-483f-8e15-5885dce3aa65

---
spring:
  profiles: qa
server:
  port: 8080

magento:
  url:
    base: https://www.gfashion2020.tk/index.php/rest/V1/
    token: integration/admin/token
    customers: customers/
    storeViews: store/storeViews/
    websites: store/websites/
    storeGroups: store/storeGroups/
    storeConfigs: store/storeConfigs/
    products: products/
    stockItems: stockItems/
    categories: categories/
    attributes: products/attributes?searchCriteria[filterGroups][0][filters][0][field]=is_filterable&searchCriteria[filterGroups][0][filters][0][value]=false&searchCriteria[filterGroups][0][filters][0][conditionType]=neq
    locale:
      us: 1
      cn: 6
    listCategories: categories/list
    parameters:
      parentIdField: parent_id
      field: searchCriteria[filterGroups][0][filters][0][field]=
      value: searchCriteria[filterGroups][0][filters][0][value]=
      recommendedDesignersParentId: 62 # the category id for designers
      recommendedBrandsParentId: 59 # the category id for brands
    designersParentId: 46
    brandsParentId: 50
  username: admin
  password: 202064_Hh


logging:
  level:
    ROOT: DEBUG
    com.gfashion: DEBUG

aws:
  dynamodb:
    accesskey: AKIA5VIRCT2GP56W4WU6
    secretkey: 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
    session_token:
    endpoint: https://dynamodb.us-east-1.amazonaws.com
    region: us-east-1
  es:
    endpoint: https://search-gfproductdomain-bd4u3hhprgsfnhwek2wihxfvxq.us-east-1.es.amazonaws.com
    accessKey: AKIA5VIRCT2GP56W4WU6
    secretKey: ozKKR7m0/We/zpQ0Qne3ERYXpXYVs4AWE8rDD3vu
    region: us-east-1
    serviceName: es
  samples:
    brands: 4d8b996e-7d31-4463-ac32-03e48af71eb9,22141eab-f9f8-43bb-bc80-3867b4fc8350,cefa93e2-05d9-4f13-8824-7532cf91a544,0b6bd4e4-d3c1-45ed-80a6-981f4b63e0e2,53c27c88-f394-4297-8244-c37766905ab1
    designers: 22f6a794-9a6f-4b1b-b5ff-78c7766f5d0e,a20fd425-aa13-4f18-834a-38bafce4031b,23fa1c1e-fbcf-466f-adf1-4fc824255954,a49ba01e-2c6f-49c4-a823-e9dcbbbeee34,629524b1-d299-4e83-b216-e99afc083764,2826d6c4-6700-41d8-8932-8d8f5d4fe261,c9d7b743-50c5-4266-9bdf-228924e311ec,20891b85-a4dd-4ece-990e-bb227e2a316c
    products: 813354b7-5dc0-4874-8231-6c4d00433709,61af3f6d-c3ad-4a44-af37-21a4e3dc3da2,cc34ed34-51de-4979-9a4d-8a79e51e8d87,60a08abf-0964-4324-a175-89baf7213145,03255fe2-ae54-48ba-b20c-a4e4f05a2004,0b41c0d7-8bca-483f-8e15-5885dce3aa65
