# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 8080

magento:
  url:
    base: https://www.gfashion2020.tk/index.php/rest/V1/
    token: integration/admin/token
    customers: customers/
    storeViews: store/storeViews/
    websites: store/websites/
    storeGroups: store/storeGroups/
    storeConfigs: store/storeConfigs/
    products: products/
    stockItems: stockItems/
    categories: categories/
    attributes: attributes/
    listCategories: categories/list
    parameters:
      parentIdField: parent_id
      field: searchCriteria[filterGroups][0][filters][0][field]=
      value: searchCriteria[filterGroups][0][filters][0][value]=
      recommendedDesignersParentId: 62 # the category id for designers
      recommendedBrandsParentId: 59 # the category id for brands
    designersParentId: 46
    brandsParentId: 50
  username: admin
  password: 202064_Hh

logging:
  level:
    ROOT: DEBUG
    com.gfashion: DEBUG

amazon:
  dynamodb:
    accesskey: AKIA5VIRCT2GP56W4WU6
    secretkey: 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
    session_token:
    endpoint: https://dynamodb.us-east-1.amazonaws.com
    region: us-east-1

---
spring:
  profiles: qa
server:
  port: 8080

magento:
  url:
    base: https://www.gfashion2020.tk/index.php/rest/V1/
    token: integration/admin/token
    customers: customers/
    storeViews: store/storeViews/
    websites: store/websites/
    storeGroups: store/storeGroups/
    storeConfigs: store/storeConfigs/
    products: products/
    stockItems: stockItems/
    categories: categories/
    attributes: products/attributes?searchCriteria[filterGroups][0][filters][0][field]=is_filterable&searchCriteria[filterGroups][0][filters][0][value]=false&searchCriteria[filterGroups][0][filters][0][conditionType]=neq
    listCategories: categories/list
    parameters:
      parentIdField: parent_id
      field: searchCriteria[filterGroups][0][filters][0][field]=
      value: searchCriteria[filterGroups][0][filters][0][value]=
      recommendedDesignersParentId: 62 # the category id for designers
      recommendedBrandsParentId: 59 # the category id for brands
    designersParentId: 46
    brandsParentId: 50
  username: admin
  password: 202064_Hh


logging:
  level:
    ROOT: DEBUG
    com.gfashion: DEBUG

amazon:
  dynamodb:
    accesskey: AKIA5VIRCT2GP56W4WU6
    secretkey: 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
    session_token:
    endpoint: https://dynamodb.us-east-1.amazonaws.com
    region: us-east-1
