# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 8080

magento:
  url:
    base: https://www.gfashion2020.tk/index.php/rest/V1/
    token: integration/admin/token
    customers: customers/
    products: products/
    categories: categories/
    attributes: attributes/
    storeConfigs: store/storeConfigs
  username: admin
  password: 202064_Hh

logging:
  level:
    ROOT: DEBUG
    com.gfashion: DEBUG

---
spring:
  profiles: qa
server:
  port: 8080

magento:
  url:
    base: https://www.gfashion2020.tk/index.php/rest/V1/
    token: integration/admin/token
    customers: customers/
    products: products/
    categories: categories/
    attributes: attributes/
  username: admin
  password: 202064_Hh

logging:
  level:
    ROOT: DEBUG
    com.gfashion: DEBUG
